spring.application.name=invenstar

cors.allowed-origins=http://localhost:4200


# replace the secret key with a secure random value in production
jwt.secret=UcyLwdsLHhal893ocDwAkqguOY8twqgHsg6FziuhmKJ
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
